name: Build for Windows

env:
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:
    inputs:
      tags:
        description: 'Build tags'

jobs:
  build_windows:
    if: ${{ github.actor == 'GuinnessShep' }}
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create virtual environment
        run: python -m venv myenv
        shell: powershell

      - name: Activate virtual environment
        run: .\myenv\Scripts\Activate.ps1
        shell: powershell

      - name: Install wxPython
        run: pip install https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.2.2a1.dev5594+f4db521a-cp311-cp311-win_amd64.whl

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: List modules and their versions
        run: pip freeze

      - name: Build application
        run: .\build.bat

      - name: List contents of dist directory
        run: ls dist

      - name: Upload Windows Artifact
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3
        with:
          name: PixelFlasher.exe
          path: dist/PixelFlasher.exe

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.11.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          allowUpdates: "true"
          draft: false
          prerelease: true

      - name: Upload Windows Artifact to release
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/PixelFlasher.exe
          asset_name: PixelFlasher.exe
          asset_content_type: application/zip
